(define vct-multiply! float-vector-multiply!)
(define vct-scale! float-vector-scale!)
(define vct-abs! float-vector-abs!)
(define vct-add! float-vector-add!)
(define vct-subtract! float-vector-subtract!)
(define vct-offset! float-vector-offset!)
(define vct-peak float-vector-peak)
(define vct-peak-and-location float-vector-peak-and-location)
(define vct-move! float-vector-move!)
(define vct-subseq float-vector-subseq)
(define vct->string float-vector->string)
(define vct* float-vector*)
(define vct+ float-vector+)
(define vct-max float-vector-max)
(define vct-min float-vector-min)
(define vct-ref float-vector-ref)
(define vct-set! float-vector-set!)
(define region->vct region->float-vector)
(define mix-vct mix-float-vector)
(define transform->vct transform->float-vector)
(define vct->channel float-vector->channel)
(define channel->vct channel->float-vector)

(define data-format sample-type)
(define mus-sound-data-format mus-sound-sample-type)
(define mus-data-format-name mus-sample-type-name)
(define mus-data-format->string mus-sample-type->string)
(define default-output-data-format (dilambda 
				    (lambda () *default-output-sample-type*)
				    (lambda (val) (set! *default-output-sample-type* val))))

