#!/bin/csh -f

# cp ~/dist/snd/snd.tar .
# tar xf snd.tar

# words I constantly missppelll
fgrep decrip *.html
fgrep accomoda *.html
fgrep pysical *.html
fgrep decrip *.c
fgrep maake *.c
fgrep maake *.html
fgrep accomoda *.c
fgrep decrip *.scm
fgrep accomoda *.scm
fgrep reponse *.[ch]
fgrep -e "the the " *.c
fgrep -e "the the " *.html
fgrep udpate *.c
fgrep udpate *.html
fgrep udpate *.scm
fgrep -e "Float* " *.[ch]
fgrep -e "float* " *.h
fgrep -e "double* " *.h
fgrep -e "int* " *.h
fgrep -e "off_t* " *.[ch]
fgrep -e " long* " *.[ch]
fgrep -e "propogat" *.[ch]
fgrep -e "propogat" *.html
fgrep -e "propogat" *.scm
grep ' \-\-$' *.html
/home/bil/cl/snd tools/va.scm

echo ' '
echo ' '
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 basic configure test                                  ----- '
echo ' -------------------------------------------------------------------------------- '

./configure --quiet --with-motif CFLAGS="-O3 -Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib" 
make
echo ' '
echo ' '

./snd --version
./snd -noinit --features "'clm 'snd-s7 'snd-motif 'sndlib"
./snd -e '(begin (load "cload.scm") (set! *cload-cflags* "-Wall"))' libm.scm libc.scm libgdbm.scm libdl.scm libgsl.scm -e '(exit)'

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 ffitest                                               ----- '
echo ' -------------------------------------------------------------------------------- '

cp tools/ffitest.c .
gcc -o ffitest ffitest.c -g3 -Wall s7.o -lm -I. -ldl
ffitest

gcc s7.c -o repl -Wall -DWITH_MAIN -DUSE_SND=0 -I. -O2 -g3 -Wl,-export-dynamic -ldl -lm

echo '#define WITH_SYSTEM_EXTRAS 0' >mus-config.h
gcc -c s7.c -o s7.o -Wall
rm s7.o
echo '#define WITH_C_LOADER 0' >mus-config.h
gcc -c s7.c -o s7.o -Wall
rm s7.o
echo '#define WITH_EXTRA_EXPONENT_MARKERS 1' >mus-config.h
gcc -c s7.c -o s7.o -Wall
rm s7.o

make clmclean
make sndinfo
make sndplay
make allclean

./configure --quiet --with-motif CFLAGS="-Wall -I/usr/X11R6/include -Wdeclaration-after-statement" LDFLAGS="-L/usr/X11R6/lib"
make allclean
make
echo ' '
echo ' '

make clmclean
make sndinfo
make sndplay
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 g++                                ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib" 
make
./snd --version
./snd -noinit --features "'clm"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 clang                                ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=/home/bil/test/llvm-3.1.src/build/Release+Asserts/bin/clang CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib" 
make
./snd --version
./snd -noinit --features "'clm"

make allclean
rm -f snd
rm -f config.cache

./configure --quiet CC=clang CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib" 
make
make allclean
rm -f snd
rm -f config.cache


echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-gui                                         ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --without-gui
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-gui                                          ---  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DWITH_MAIN" --without-gui
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-audio                                         ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --without-audio
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-audio C++                                       ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --without-audio CC=g++
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-gui --with-oss                              ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --without-gui --with-oss
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'oss"

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-gui --with-gmp                              ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --without-gui --with-gmp --with-ladspa CFLAGS="-Wall -I/usr/local/include"
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'gmp"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 -without-gui --with-ladspa ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -I/usr/local/include" --without-gui --with-ladspa
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'snd-s7"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-gtk                                             ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-O3 -Wall -I/usr/X11R6/include" --with-gtk
make
echo ' '
echo ' '
./snd --version
/home/bil/cl/snd tools/va.scm
./snd -noinit --features "'clm 'snd-gtk 'snd-s7"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 g++ --with-gtk --disable-deprecated                   ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ CFLAGS="-Wall -I/usr/X11R6/include" --with-gtk --disable-deprecated
make allclean
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'snd-s7"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --with-gtk --std=c++11                             ---  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ --with-gtk CFLAGS="-std=c++11 -Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --with-gtk --with-gsl                              ---  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ --with-gtk --with-gsl CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'gsl"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth                                           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --quiet --with-motif --with-forth
make
./snd --version
./snd -noinit --features "'clm 'snd-forth 'snd-motif"

make clmclean
make sndinfo
make sndplay
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth  --with-motif --with-gl ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-forth  --with-motif --with-gl LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-forth 'xm 'gl"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth --with-gtk       --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-forth --with-gtk  LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'xg 'gl"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth --without-gui                              --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-forth --without-gui LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-forth 'snd-nogui"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-extension-language                          ----  '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --without-extension-language
make
echo ' '
echo ' '
./snd --version
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-extension-language --with-gtk               ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --without-extension-language --with-gtk
make
echo ' '
echo ' '
./snd --version
rm -f sndinfo
make sndinfo
./sndinfo test.snd
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-extension-language --with-gl         ------  '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --without-extension-language --with-motif --with-gl
make
echo ' '
echo ' '
./snd --version
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-extension-language g++                      ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --without-extension-language  CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include"
make
echo ' '
echo ' '
./snd --version
make allclean

rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                  --with-gtk                                            ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"  --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' -----                GTK_DISABLE_DEPRECATED G_DISABLE_DEPRECATED GDK_DISABLE_DEPRECATED --with-gtk  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CFLAGS="-Wall -I/usr/X11R6/include -D_FORTIFY_SOURCE=2" --with-gtk 
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'xg"

make allclean
rm -f snd
rm -f sndinfo
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-gsl                           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DDEBUGGING" --with-motif --with-gsl
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'gsl 'snd-motif"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-gmp                                              ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-gmp
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-motif 'gmp"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                WITH_PURE_S7  --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DWITH_PURE_S7=1"
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-motif"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                  editres                              ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"  --with-motif --with-editres --disable-deprecated
make
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++                                    ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --with-motif LDFLAGS="-L/usr/X11R6/lib" --quiet CC=g++  CFLAGS="-Wall -I/usr/X11R6/include"
make

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-gtk --with-gmp                                  ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-gtk --with-gmp CFLAGS="-Wall"
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'gmp"

echo ' '
echo ' '
make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-ruby                                            ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby --with-motif 
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_ruby, :snd_motif"

make clmclean
make sndinfo
make sndplay
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 g++ --with-ruby                                        ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby
make
./snd --version
./snd -noinit --features ":clm, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-ruby  --with-gl --with-alsa '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DDEBUGGING" --with-ruby  --with-motif --with-gl --with-alsa
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :alsa, :snd_ruby, :gl"

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-ruby --with-gtk                                 ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_gtk, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --with-ruby --with-gtk --with-alsa                 ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ --with-ruby --with-gtk --with-alsa
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :alsa, :snd_gtk, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-ruby  --with-gtk --without-gsl '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DDEBUGGING" --with-ruby  --with-gtk --without-gsl
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_ruby, :snd_gtk"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                GTK_DISABLE_DEPRECATED G_DISABLE_DEPRECATED GDK_DISABLE_DEPRECATED --with-ruby  --with-gtk '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -D_FORTIFY_SOURCE=2" --with-ruby  --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd-gtk, :xg"

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-ruby --without-gui --without-fftw                --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby --without-gui --without-fftw
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_nogui, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-ruby --without-gui                             ----- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DDEBUGGING" --with-ruby --without-gui
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_nogui, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --with-ruby --without-gui        ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DDEBUGGING" --with-ruby --without-gui 
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_nogui, :snd_ruby"
make allclean

rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++                                                      --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-motif --with-ladspa CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -I/usr/local/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-s7 'snd-motif 'snd-ladspa 'sndlib"
make sndinfo
make sndplay
./sndinfo test.snd
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --with-gtk                                          ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ --with-gtk CFLAGS="-Wall"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --without-gui                                       ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --quiet CC=g++ --without-gui
make
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'snd-s7"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --without-extension-language                     ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet CC=g++ --without-extension-language
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++  --without-gsl --with-alsa '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --quiet CC=g++  --without-gsl --with-alsa
make
./snd --version
./snd -noinit --features "'clm 'alsa 'xm"
make allclean
echo ' '
echo ' '

make allclean
rm -f snd
rm -f config.cache
rm -f sndinfo

echo ' -------------------------------------------------------------------------------- '
echo ' -----                sndlib                                                 ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make sndinfo
sndinfo oboe.snd
sndinfo test.snd
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-gui                                          ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --without-gui
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'snd-s7"

make allclean
rm -f snd
rm -f config.cache
rm -f makefile
rm -f mus-config.h

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                 -DXM_DISABLE_DEPRECATED              ----- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet  LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -DXM_DISABLE_DEPRECATED -Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'xm"
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                 --with-ruby -DXM_DISABLE_DEPRECATED   ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet  --with-ruby LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -DXM_DISABLE_DEPRECATED -Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features ":clm, :snd_ruby"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-gui --without-extension-language          ----- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --without-gui --without-extension-language --quiet
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-extension-language  --with-gl '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --without-extension-language  --with-motif --with-gl --quiet
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                 --with-gl --with-gl2ps         ------ '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"  --with-motif --with-gl --quiet --with-gl2ps --without-gsl
make
./snd --version
./snd -noinit --features "'clm 'xm 'gl2ps"
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-extension-language --with-gtk                ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --without-extension-language --with-gtk  --quiet
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-portaudio                                       ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --with-portaudio --quiet
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean



echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-jack                                       ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --with-jack --with-alsa --quiet
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean



echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-pulseaudio                                      ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --with-pulseaudio --quiet
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean



cp ~/sndlib/* .
echo ' -------------------------------------------------------------------------------- '
echo ' -----                sndlib tests                                           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-Wall"
make

cp tools/exs7.c .
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 1 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX1 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 2 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX2 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 3 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX3 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 4 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX4 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 5 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX5 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 6 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX6 -ldl

# make clean
# echo ' -------------------------------------------------------------------------------- '
# echo ' -------------------------------- sndlib ruby -------------------------------- '
# echo ' -------------------------------------------------------------------------------- '
# ./configure --quiet --with-ruby
# make
make clean
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- sndlib forth -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-forth
make
make clean
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- sndlib s7 c++ -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++
make
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 1 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX1 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 2 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX2 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 3 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX3 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 4 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX4  -ldl /home/bil/test/sndlib/libsndlib.a -lgsl -lgslcblas -lasound
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 5 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX5 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 6 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX6 -ldl
rm exs7
rm exs7.o
make clean
